### PR TITLE
[11.9] Add optional parameter "access_level" to create project access token

### PR DESCRIPTION
**Pull request by dododedodonl**
Add the `access_level` parameter, as specified in the [documentation](https://docs.gitlab.com/ee/api/project_access_tokens.html#create-a-project-access-token).

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Sorry that it took so long to get to this. I tried to re-open this, but it looks like the branch has been deleted. Would you mind to open a new PR, please?

**Comment by dododedodonl** [comment]
I think I reopened it here already: https://github.com/GitLabPHP/Client/pull/731

**Comment by GrahamCampbell** [comment]
Thanks. 👍

**Comment by GrahamCampbell** [comment]
v11.9.0 has now been released, with this change, and many others, including PHP 8.2 support. 🚢

**Pull request closed without merging**
