### PR TITLE
Switch to PSR-17 and PSR-18

### PR DESCRIPTION
**Pull request by GrahamCampbell**
HTTP Plug 1 is deprecated and HTTP Plug 2 recommends only using PSR-17 and PSR-18, rather than the old interfaces. Moreover, Guzzle 7 only implements the new interfaces, so this will be a blocker for anyone wanting to upgrade from Guzzle 6 to 7 and use this package at the same time. I've also fixed a bunch of static analysis errors and added support for cache plugins (just like in KnpLabs/php-github-api).

Note that these changes require bumping the next version of this package to 10.0.0, which is fine. Upgrading shouldn't be hard for people. ;)

---

Related: https://github.com/KnpLabs/php-github-api/pull/885, https://github.com/BitbucketAPI/Client/pull/39, https://github.com/BitbucketAPI/Client/pull/53, https://github.com/php-http/discovery/pull/175.

### CODE REVIEW

**Comment by m1guelpf** [comment]
Is this ready for merging?

**Comment by GrahamCampbell** [comment]
Before merging, I'd recommend you create a new branch "2.17" based off of the current master, so the latest changes since 2.16.0 can appear in a 2.x release, and possibly future bug fixes into the 2.x series.

**Comment by GrahamCampbell** [comment]
Before merging, I'd recommend you branch of a `9.17` branch from `master`. :)

**Comment by GrahamCampbell** [comment]
Since this PR will make `master` become `10.0`.

**Comment by GrahamCampbell** [comment]
@m1guelpf Yes, however before merging, I'd recommend you branch of a `9.17` branch from `master`, since this PR will make `master` become `10.0`. :)

**Pull request merged**
