### PR TITLE
[11.9] Allow `update_at` order by in `Projects::pipelines`

### PR DESCRIPTION
**Pull request by jdecool**
According to [this documentation](https://docs.gitlab.com/ee/api/pipelines.html#list-project-pipelines) order by `update_at` value is allowed.

### CODE REVIEW

**Review by GrahamCampbell — CHANGES_REQUESTED** [review]
Please update the documentation on line 340.

**Comment by jdecool** [comment]
> Please update the documentation on line 340.

✅

**Comment by jdecool** [comment]
🖖🏼  Hey @GrahamCampbell , don't want to put pressure, just want to know if you plan to merge this PR ?

**Comment by jdecool** [comment]
Hi @GrahamCampbell, do you think this is mergeable ?

**Comment by GrahamCampbell** [comment]
Thanks for working on this. 🍻

**Comment by GrahamCampbell** [comment]
v11.9.0 has now been released, with this change, and many others, including PHP 8.2 support. 🚢

**Pull request merged**
