### PR TITLE
Create Project for User

### PR DESCRIPTION
**Pull request by cheiff**
Hi, 

this time without .gitignore. 

Thanks, regards.

### CODE REVIEW

**Comment by m4tthumphrey** [comment]
Sorry to be a pain but it's still in the PR so will show at latest commit. Can you rebase with only the relevant commit please!

**Comment by vadikk006** [comment]
hey,  im not find how fork project in API, its possible?

**Comment by m4tthumphrey** [comment]
Hi @vadikk006! No this has not been merged so the functionality is not currently in the library. I will add the changes from this PR into the repository over the weekend so it will be available Monday.

**Comment by cheiff** [comment]
See #94

**Pull request closed without merging**
