### PR TITLE
[11.5] Add support for freeze periods

### PR DESCRIPTION
**Pull request by peterjaap**
Gitlab introduced freeze periods in Gitlab 13.0, see API documentation here; https://gitlab.elgentos.nl/help/api/freeze_periods.md

### CODE REVIEW

**Review by GrahamCampbell — CHANGES_REQUESTED** [review]
Thanks for taking the time to prepare this, and sorry for my delayed review. Are you able to add some tests please?

**Comment by GrahamCampbell** [comment]
Friendly ping @peterjaap.

**Comment by peterjaap** [comment]
@GrahamCampbell sorry I don't have the time / headspace to write tests atm.

**Comment by GrahamCampbell** [comment]
No problem, if you wanna come back to this later in the year, or not at all, both are fine. :)

**Pull request closed without merging**
