### PR TITLE
[11.2] Implemented user memberships

### PR DESCRIPTION
**Pull request by alexandre67fr**
According to https://docs.gitlab.com/ee/api/users.html#user-memberships-admin-only

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks for this. Could you please:

1. Rebase against `11.1` and add an entry to the change log;
2. Add a unit test covering this new code.

**Comment by GrahamCampbell** [comment]
Please mark this as "ready for review" when you are done. :)

**Comment by alexandre67fr** [comment]
Hey Graham, sure I’ll add a couple of unit tests this weekend 👍

**Comment by GrahamCampbell** [comment]
Friendly ping @alexandre67fr. :)

**Comment by alexandre67fr** [comment]
Hey @GrahamCampbell sorry for the late reply, I've added PHPUnit tests

If it's all good, I can create another mini-PR request for the option `last_activity_after` in [GET /projects](https://docs.gitlab.com/ee/api/projects.html), which is missing in the source code. It's very useful for querying for updated projects. We've got 2,000+ repositories, and `last_activity_after` option can speed up the update process dramatically. Thanks

**Comment by GrahamCampbell** [comment]
Thanks. 🍻

**Pull request merged**
