### PR TITLE
[11.9] Add support for `access_level` in `Projects::createProjectAccessToken`

### PR DESCRIPTION
**Pull request by dododedodonl**
Add the `access_level` parameter, as specified in the [documentation](https://docs.gitlab.com/ee/api/project_access_tokens.html#create-a-project-access-token).

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks for the PR. 👍

**Comment by GrahamCampbell** [comment]
It looks like the tests are failing here. I've had to revert this.

**Comment by dododedodonl** [comment]
@GrahamCampbell I'm not sure what the problem is, I do not use psalm myself and wrote the code quite some time ago. It looks like it has to do something with the type that is specified in the doctag. It looks correct to me though, as it uses an int in the testcase.

**Comment by GrahamCampbell** [comment]
The failure was not psalm, but phpunit (at least, the psalm failure was not related to this PR).

**Comment by GrahamCampbell** [comment]
https://github.com/GitLabPHP/Client/actions/runs/4343185802/jobs/7584915249

**Comment by dododedodonl** [comment]
I am not that used to github, and missed the second action job. While fixing this I mixed up another local version of the sdk, and it was easier to create a new branch.

**Pull request merged**
