### PR TITLE
Added CreateProject for user and CreateKey for User

### PR DESCRIPTION
**Pull request by cheiff**
Hi,
sorry, I have been buried in work. I have added another function.
I have rebased the repo, this time everything should be ok.
Thanks, regards

### CODE REVIEW

**Comment by cheiff** [comment]
Ugh , I wrote project with "y". Do I have to re do it again?

**Comment by m4tthumphrey** [comment]
Haha no but there are CS issues; no spaced between arguments! Fix that and push and I'll merge. Don't worry about rebasing that one.

**Comment by cheiff** [comment]
OK, fixed all that, "y" included. Let's see if finally I am able to add my two cents...

**Comment by m4tthumphrey** [comment]
:+1:

**Pull request merged**
