### PR TITLE
[11.1] Added CI schedule variables endpoints

### LINKED ISSUE #508: Scheduled pipeline variables
Is there currently support for scheduled pipeline variables? It seems to be part of the Gitlab API (https://docs.gitlab.com/ee/api/pipeline_schedules.html#create-a-new-pipeline-schedule-variable), but those calls don't seem to be part of the Schedules class. Is there a plan to implement the scheduled pipeline variables calls?
Thanks.

### PR DESCRIPTION
**Pull request by mgrundkoetter**
I added the create/edit/delete Endpoints described in https://docs.gitlab.com/ee/api/pipeline_schedules.html#create-a-new-pipeline-schedule-variable.

---

Closes #508.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks for the PR @mgrundkoetter. Are you able to rebase and finish this off please?

**Comment by mgrundkoetter** [comment]
All the checks are green now, can you merge/rebase it? I don't really gut your git branch structure, sorry.

**Comment by GrahamCampbell** [comment]
You can do `git fetch upstream && git pull --rebase upstream 10.2 && git push --force`.

**Comment by GrahamCampbell** [comment]
Could you also add some tests please?

**Comment by mgrundkoetter** [comment]
I did the rebase. But when I try to run `make install` an error is raised:

> Unable to locate a valid CA certificate file. You must set a valid 'cafile' option.
> A valid CA certificate file is required for SSL/TLS protection.
> You can disable this error, at your own risk, by setting the 'disable-tls' option to true.
> 
>                                                              
>   [Composer\Downloader\TransportException]                   
>   The configured cafile was not valid or could not be read.

**Comment by GrahamCampbell** [comment]
Is this fixed by running `docker pull registry.gitlab.com/grahamcampbell/php:7.4-base`?

**Comment by mgrundkoetter** [comment]
> Is this fixed by running `docker pull registry.gitlab.com/grahamcampbell/php:7.4-base`?

Sorry, this doesn't help, the error still appears:

> Unable to locate a valid CA certificate file. You must set a valid 'cafile' option.
> A valid CA certificate file is required for SSL/TLS protection.
> You can disable this error, at your own risk, by setting the 'disable-tls' option to true.
> 
>                                                              
>   [Composer\Downloader\TransportException]                   
>   The configured cafile was not valid or could not be read.  
>                                                              
> 
> make: *** [install] Error 1

Seems to me, that the error is raised by composer trying to download something, not by the docker command.

**Comment by GrahamCampbell** [comment]
You should be using composer from within docker, not your local version of composer? `make install` should do that.

**Comment by GrahamCampbell** [comment]
I can't see why this wouldn't work, because you and I should have identical docker images. Anything machine specific should not matter.

**Comment by mgrundkoetter** [comment]
`make install` is what I called to get this error, so yes, the error comes from inside the container. If I manually call the `docker run` command without the `--rm` flag, I see exactly this when I use `docker logs` on the (exited) container.

In the makefile, you map the local directory ~/.composer inside the container. This is the reason it does not work as those directories ARE machine specific. If I change this to a named volume, everything works fine...

**Comment by GrahamCampbell** [comment]
Ohhhh, do you have SSL config in your `~/.composer` config json?

**Comment by GrahamCampbell** [comment]
Closing due to inactivity. I don't have capacity to take this on and finish up. I would, of course, review a new PR with appropriate corrections.

**Comment by mgrundkoetter** [comment]
All the checks are green, what are those "appropriate corrections"?

**Comment by GrahamCampbell** [comment]
The comments I made on 26th October.

**Comment by mgrundkoetter** [comment]
I added 3 test cases.

**Comment by GrahamCampbell** [comment]
Can you rebase against 10.4 please?

**Comment by GrahamCampbell** [comment]
Oh, sorry I didn't see that you'd done this because you didn't un-mark the PR has draft, so it didn't make it into the 10.4.0 and 11.0.0 releases. This will now be targeting the 11.1.0 release, for release in early 2021 (probably January).

**Comment by GrahamCampbell** [comment]
Great work here. 🍻

**Comment by GrahamCampbell** [comment]
In the meanwhile, you can install this using `^11.1@dev`.

**Pull request merged**
