### PR TITLE
Add hasLabel method to Issue model

### PR DESCRIPTION
**Pull request by KeithYeh**
- Add hasLabel method for Issue model
- Remove duplicate environments() method in `lib/Gitlab/Client.php`

### CODE REVIEW

**Comment by fbourigault** [comment]
Master have changed a lot since you opened this PR. Could you rebase it?

**Comment by KeithYeh** [comment]
@fbourigault I rebase my branch and reduce the change scope. Please take a look thank you.

**Comment by m1guelpf** [comment]
@KeithYeh Could you add a test?

**Comment by KeithYeh** [comment]
@m1guelpf I just add some test case for Issue model. Please take a look, thanks.

**Comment by m1guelpf** [comment]
@KeithYeh Please rebase

**Comment by KeithYeh** [comment]
@m1guelpf rebase done, please take a look.

**Pull request merged**
