### PR TITLE
Add method impersonate() to Client to act on a users behalf

### PR DESCRIPTION
**Pull request by spawnia**
This function conveniently takes care of both creating and revoking the impersonation token and allows making API calls while authenticated as the user.

If this idea is something you want to pursue further, I am happy to add tests and documentation.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Please send new features to the 9.19 branch.

**Comment by spawnia** [comment]
> Please send new features to the 9.19 branch.

Thanks, done ~~https://github.com/GitLabPHP/Client/pull/562~~ https://github.com/GitLabPHP/Client/pull/563

**Comment by glensc** [comment]
@spawnia:
1. your link points back to this PR itself
2. you don't need to create new PR, you can edit the target branch

**Comment by spawnia** [comment]
@glensc thanks, updated the link.

I found it easier to start a new one, since this one is based on 10.0.

https://github.com/GitLabPHP/Client/pull/563

**Pull request closed without merging**
