### PR TITLE
added Result Paginator

### PR DESCRIPTION
**Pull request by radutopala**
via a PaginatorListener
and fixed issue fetching within a project, due to API changes

### CODE REVIEW

**Comment by m4tthumphrey** [comment]
Thanks!

Any reason you moved the namespace line? Also can you update the tests as they are failing due to the API change.

**Comment by radutopala** [comment]
For namespaces, just following http://www.php-fig.org/psr/psr-1/. First line contains usually just `<?php`.

I'll check the tests.

**Comment by vinkla** [comment]
IMO we should follow PSR-1 and PSR-2 but not just in one class. If we're going to change we should change the entire library and not just one class.

@m4tthumphrey maybe you could add support for [StyleCI](https://styleci.io/)? It will automagically fix PHP standards.

**Comment by radutopala** [comment]
I could run myself the `php-cs-fixer`, if you'd like that.

**Comment by vinkla** [comment]
Yeah, that would be one way to go but not in this PR.

**Comment by m4tthumphrey** [comment]
There is nothing in the PSR about which line the namespace declaration has to be on and I prefer it on the top line (just keeps it more clean IMO).

**Comment by radutopala** [comment]
There is no explicit saying on this, but:

screenshot 2016-02-01 13 54 46
screenshot 2016-02-01 13 54 57

IMHO, as I'm coming from the Symfony community myself, which is a trend setter, I can say that I've never seen the namespace declaration on the same line as `<?php`. You can check https://github.com/symfony/symfony/blob/master/src/Symfony/ for yourself.

**Comment by vinkla** [comment]
Yeah I agree with @radutopala, this is quite common nowadays.

**Comment by m4tthumphrey** [comment]
Yeh I get that its not common (was just saying that I prefer same line) and I don't mind changing it but only if all files are changed in a separate commit.

**Comment by vinkla** [comment]
@m4tthumphrey maybe you could add StyleCI? It can update the repository to PSR-2 standards with just some clicks.

**Comment by m4tthumphrey** [comment]
Can anyone else do it? @vinkla

**Comment by vinkla** [comment]
No, sorry. It has to be the owner of the repository.

**Comment by m4tthumphrey** [comment]
Can I add you to the project? @vinkla

**Comment by vinkla** [comment]
Yeah, but I don't think it will work anyhow.

@jbrooksuk this is correct right?

**Comment by vinkla** [comment]
@m4tthumphrey you could add me and then I can help you setup PHP-CS-Fixer if you want?

**Comment by jbrooksuk** [comment]
You can't add StyleCI without being an owner of the repo I'm afraid.

**Comment by m4tthumphrey** [comment]
Ok well can we just forget about the style and leave the namespaces at the top of the file for this PR, I will then get around to sorting the style out in the next major release.

**Comment by radutopala** [comment]
Or I can just update all files now in this PR with the namespace on the next line, there aren't so many files there. Sorry, but reverting to what was before with be itchy more me :)

**Comment by jbrooksuk** [comment]
Changing CS should be done in a separate PR.

**Comment by vinkla** [comment]
Yeah, the CS changes should not be implemented here. We should open a new PR for that.

**Comment by radutopala** [comment]
@m4tthumphrey @vinkla guys, please check, I've updated the PR.

**Comment by vinkla** [comment]
PSR-wise it looks much better :+1:

**Comment by radutopala** [comment]
Seems like the CI is failing just here: https://travis-ci.org/m4tthumphrey/php-gitlab-api/jobs/107742337, due to openssl. Any thoughts?

**Comment by radutopala** [comment]
Also, I can push a new PR with some PSR updates, just ping me.

**Comment by m4tthumphrey** [comment]
@radutopala That issue is happening for every build, not sure why yet. Don't think it is specific to this project though.

**Comment by radutopala** [comment]
@m4tthumphrey so then I guess we're good to go :)

**Comment by muskie9** [comment]
Hi all, just wondering if there's movement on this ticket? I recently started using this for a project I'm doing and works well, however I did come across the need for the pagination feature as our gitlab account has more than the maximum result limit for a request. On another note, if I have general questions is there some place to raise those rather than a new issue tix? Thanks!

**Comment by radutopala** [comment]
@muskie9 you could use this from packagist, until they merge the PR: `"radutopala/php-gitlab-api": "dev-master"`

**Comment by muskie9** [comment]
Ah, perfect! Thanks @radutopala!

**Comment by m4tthumphrey** [comment]
@radutopala Do you fancy being added to the project to help manager PRs etc?

@muskie9 If your questions about gitlab itself check out [their forum](https://forum.gitlab.com/). If it's about the lib just drop me an email github [[ at ]] m4tt [[ dot ]] co

**Comment by radutopala** [comment]
Sure thing, add me in.

**Comment by radutopala** [comment]
@m4tthumphrey will someone else maintain this project? tx

**Pull request merged**
