### PR TITLE
Updated addVariable() and updateVariable()

### PR DESCRIPTION
**Pull request by c33s**
updated `addVariable()` and `updateVariable()` to match current gitlab api (added `$protected `$environment_scope`)
 
- https://docs.gitlab.com/ee/api/project_level_variables.html#create-variable
- https://docs.gitlab.com/ee/api/project_level_variables.html#update-variable

### CODE REVIEW

**Comment by c33s** [comment]
an idea also would be to do some input validation with `webmozart/assert`
```
Assert::nullOrBoolean($protected)
Assert::nullOrString($environment_scope)
```

**Comment by c33s** [comment]
@m1guelpf what about the suggestion to add assert? this would add a new dependency to the code but will improve the error detection.  but it is a very stable dependency (26M downloads ). it is from @webmozart inpired by  beberlei/assert.

**Comment by m1guelpf** [comment]
@c33s I feel like if we wanted to do something like assert does, we would add typehints. Also, I don't see the value of validating input in an API client, if something is wrong, the GitLab server will throw an error.

**Comment by fbourigault** [comment]
We started using `OptionsResolver` to validate filters/payloads.

**Comment by c33s** [comment]
anything missing from my side that you can merge this PR?

**Comment by fbourigault** [comment]
Thank you!

**Pull request merged**
