### PR TITLE
Allow getting merge requests which would close an issue

### PR DESCRIPTION
**Pull request by violuke**
See https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/issues.md#list-merge-requests-that-will-close-issue-on-merge

Please merge asap, thank you

### CODE REVIEW

**Comment by fbourigault** [comment]
Hello, could you add an unit test and fix code style according to styleci?

**Comment by violuke** [comment]
Thanks @fbourigault, I've sorted those now. Thanks.

**Comment by fbourigault** [comment]
Thank you!

**Comment by violuke** [comment]
Thanks. Would you mind releasing 9.4.0 with this included so I can clean up my composer file?

**Pull request merged**
