### PR TITLE
Updating merge request api

### PR DESCRIPTION
**Pull request by biggins**
Added scope to merge request api and have made project_id optional on the merge request which was added in Gitlab 9.5 https://docs.gitlab.com/ee/api/merge_requests.html#list-merge-requests

### CODE REVIEW

**Comment by biggins** [comment]
@m4tthumphrey is there a way I can re-run travis given it failed before it got to the code

**Comment by m1guelpf** [comment]
@biggins Retried the build

**Comment by GrahamCampbell** [comment]
Ping @biggins.

**Comment by glensc** [comment]
rebased as new PR: https://github.com/m4tthumphrey/php-gitlab-api/pull/503

**Comment by GrahamCampbell** [comment]
Moving discussions to the new PR.

**Pull request closed without merging**
