### PR TITLE
Add optional parameter first_parent to the commits endpoint

### PR DESCRIPTION
**Pull request by dhzavann**

### CODE REVIEW

**Comment by glensc** [comment]
can you check whether the other PR does the same:
- https://github.com/m4tthumphrey/php-gitlab-api/pull/502

I'm wondering does the boolean normalized break something or not?

**Comment by dhzavann** [comment]
@glensc Hi, I was thinking of adding the normalization more or less just like that, but decided not to just because the other parameters in the function didn't use it for some reason and I didn't want to spend the time digging into why.

My guess is that it was just an oversight when those were added and that your PR is better.

**Comment by glensc** [comment]
@dhzavann can you confirm the boolean normalization is valid (in my PR) and close your PR?

**Comment by GrahamCampbell** [comment]
Thanks for your work on this. I think this is superseded by https://github.com/m4tthumphrey/php-gitlab-api/pull/502.

**Pull request closed without merging**
