### PR TITLE
Add tags API

### PR DESCRIPTION
**Pull request by cizel**
add tags api

### CODE REVIEW

**Comment by cizel** [comment]
\Gitlab\Api::Tags
  Methods: 100.00% ( 4/ 4)   Lines: 100.00% (  4/  4)

Projects not pass

**Comment by donkidd** [comment]
To fix your build you will need to update the test 

Gitlab\Tests\Api\ProjectsTest::shouldGetOwnedProjects test.

**Comment by cizel** [comment]
@m4tthumphrey  Can merge my branch?

**Comment by m4tthumphrey** [comment]
Thanks!

**Pull request merged**
