### PR TITLE
Added the ability to authenticate using an OAuth token

### PR DESCRIPTION
**Pull request by Leenug**
http://doc.gitlab.com/ce/integration/oauth_provider.html

### CODE REVIEW

**Comment by m4tthumphrey** [comment]
Oh yeh, I'd forgotten about Oauth support....

Can you squash the commits into one please :)

**Comment by m4tthumphrey** [comment]
@Leenug Are you ok to squash the commits?

**Comment by Leenug** [comment]
Sorry for the delay, should be squashed now :)

**Comment by m4tthumphrey** [comment]
Thanks man!

**Pull request merged**
