### PR TITLE
[11.9] Add group and project iterations

### PR DESCRIPTION
**Pull request by macbookandrew**
add support for [groups iterations](https://docs.gitlab.com/ee/api/group_iterations.html) and [project iterations](https://docs.gitlab.com/ee/api/iterations.html)

### CODE REVIEW

**Comment by macbookandrew** [comment]
@GrahamCampbell bump 😊

**Comment by GrahamCampbell** [comment]
Sorry that it took so long to get to this. I tried to re-open this, but it looks like the branch has been deleted. Would you mind to open a new PR, please?

**Comment by macbookandrew** [comment]
@GrahamCampbell actually, see #730. I created that after the stalebot closed this one

**Comment by GrahamCampbell** [comment]
Thanks. 👍

**Comment by GrahamCampbell** [comment]
v11.9.0 has now been released, with this change, and many others, including PHP 8.2 support. 🚢

**Pull request closed without merging**
