### PR TITLE
Remove PHP 5.3 versions from the travis build file

### PR DESCRIPTION
**Pull request by EdwinHoksberg**
This makes sure the builds can successfully run again.

As discussed in #54

### CODE REVIEW

**Comment by m4tthumphrey** [comment]
5.3 was actually ok, was just 5.3.3...

**Comment by EdwinHoksberg** [comment]
Yes I know, but I thought you wanted to drop 5.3 entirely? If not i'll add it back :)

**Comment by m4tthumphrey** [comment]
5.3 support has come up before and whilst I agree that everyone should be on _at least_ 5.4, arguably 5.6, I don't feel it's necessary to force >= 5.4 for the sake of it. There's nothing > 5.4 that we need in this lib yet so we may as well support 5.3 for now.

Yeh if you could add 5.3 back that'd be great, can finally get rid of the `build:error` button!

**Comment by EdwinHoksberg** [comment]
Yeah I agree with you, I've added it back :+1:

**Comment by m4tthumphrey** [comment]
👍

**Pull request merged**
