### PR TITLE
[9.18] Extended pipeline- and added trigger-model along trigger creation functionality

### PR DESCRIPTION
**Pull request by arnegroskurth**
Has to be considered WIP as the trigger creation currently still throws an exception when running against an actual GitLab instance: `PHP Fatal error:  Uncaught Gitlab\Exception\RuntimeException: description is missing in .../php-gitlab-api/lib/Gitlab/HttpClient/Plugin/GitlabExceptionThrower.php:49`

By already submitting this MR I am asking for help with this problem as to me it looks like I am using the `Gitlab\Api\AbstractApi#post()` function in `Gitlab\Api\Projects#createTrigger()` just like anywhere else.

For reproduction:

```php
<?php
// test-trigger-creation.php

require_once __DIR__ . '/vendor/autoload.php';


$gitlabClient = Gitlab\Client::create('...');
$gitlabClient->authenticate('...', \Gitlab\Client::AUTH_HTTP_TOKEN);

$gitlabClient->projects->createTrigger(1234, 'foobar');
```

Working CURL equivalent:
```bash
$ curl -vvv --request POST --header "PRIVATE-TOKEN: ..." --form description="foo bar" "https://.../api/v4/projects/1234/triggers"
```

resolves: #307, #514

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks for the PR @arnegroskurth. Could you cherry pick your changes so they are based on the `9.18` branch please. I am currently unable to change the default branch until this repo is transferred to its new home in a GitHub organisation, so for today, it's a little confusing for new contributors. The master branch is for `10.0` development. // cc @m4tthumphrey

**Comment by arnegroskurth** [comment]
@GrahamCampbell I'm not sure how to do this. I tried to rebase onto the 9.18 branch but the unrelated commits are still there. Help?

**Comment by GrahamCampbell** [comment]
Do this first:

```
git reset 05fa080b35f74a0c842c1e4c61b315487f6f145c
git stage .
git commit -m "Extended pipeline- and added trigger-model along trigger creation functionality"
git push --force
```

That will then give you a single commit containing your work. Note down it's hash, which I will call `<hash>` in the next part:

```
git reset --hard upstream/9.18
git cherry-pick <hash>
git push --force
```

Now you have reset your codebase to the 9.18 branch, and then applied your changes.

**Comment by arnegroskurth** [comment]
@GrahamCampbell 

Done. Thank you for the help!

**Comment by GrahamCampbell** [comment]
I've fixed the type issues with the project ID across the codebase, and merged the latest code into your branch, updating the project id types you added too. This should fix PHPStan's complaints. :)

**Comment by GrahamCampbell** [comment]
> Has to be considered WIP as the trigger creation currently still throws an exception when running against an actual GitLab instance: PHP Fatal error: Uncaught Gitlab\Exception\RuntimeException: description is missing in .../php-gitlab-api/lib/Gitlab/HttpClient/Plugin/GitlabExceptionThrower.php:49

Is this still the case? I can't see anything wrong with the current code.

**Comment by arnegroskurth** [comment]
@GrahamCampbell The error now disappeared so is suspect that it is related to diffs between the master and the 9.18 branch.

Unfortunately I don't see a way to write a test for this without having to spin up an actual gitlab instance.

**Comment by GrahamCampbell** [comment]
Yeh, that's a problem we don't yet have a solution for. Maybe one day will have the test suite load up a dockerised version of gitlab and actually test some of the endpoints against it, for real! That's certainly out of scope of this PR . ;)

This PR looks great. Thanks for working on it. 🍻

**Comment by GrahamCampbell** [comment]
This will be included in the 9.18.0 release, which will likely come out next week. 🚀

**Pull request merged**
