### PR TITLE
Added method to retrieve issues closed by a merge request

### PR DESCRIPTION
**Pull request by cdaguerre**

### CODE REVIEW

**Comment by m1guelpf** [comment]
@cdaguerre I've solved your merge conflicts. Is this ready for merge?

**Comment by fbourigault** [comment]
Travis is still complaining about failed build and, according to Github, there is still a merge conflict.

**Comment by m1guelpf** [comment]
@fbourigault Those conflicts were caused by the merge of #201, solved.
@cdaguerre Could you look at the Travis build?

**Comment by cdaguerre** [comment]
Tests fixed

**Pull request merged**
