### PR TITLE
Added functions to support the activate and deactivate methods

### PR DESCRIPTION
**Pull request by FSD-Christian-ADM**
The methods provided by the REST-AAPI hat no counterpart in this library

### CODE REVIEW

**Comment by FSD-Christian-ADM** [comment]
I am not sure why the CI check fails?

**Comment by GrahamCampbell** [comment]
You can apply the diff StyleCI gives you using git.

**Comment by GrahamCampbell** [comment]
Looks to me like you used 3 spaces for indentation instead of 4.

**Comment by FSD-Christian-ADM** [comment]
@GrahamCampbell 
thanks for the pointer! This was a classic tabs vs. spaces mixup. now all tests passed

**Comment by GrahamCampbell** [comment]
Merged as part of https://github.com/GitLabPHP/Client/pull/662.

**Pull request closed without merging**
