### PR TITLE
[9.18] Fixed typo

### LINKED ISSUE #359: Invalid encoding type 'test'
I think this is a typo 
https://github.com/marcelovani/php-gitlab-api/blob/master/lib/Gitlab/Api/Repositories.php#L240
It probably should be 'text'

### PR DESCRIPTION
**Pull request by marcelovani**
Closes #359.

### CODE REVIEW

**Comment by m1guelpf** [comment]
Can we add a test to make sure this doesn't get typo'd again?

**Comment by GrahamCampbell** [comment]
Ping @marcelovani or @m1guelpf to implement this test.

**Comment by glensc** [comment]
I would rather just go and merge than wait another two years and find that the original reporter is still not interested anymore.

**Comment by GrahamCampbell** [comment]
Thank you. :)

**Comment by GrahamCampbell** [comment]
Backported this to 9.17.x series. Released in 9.17.1.

**Pull request merged**
