### PR TITLE
[11.5] Add addShare method

### PR DESCRIPTION
**Pull request by peterjaap**
To be able to share groups with groups. See documentation; https://docs.gitlab.com/ee/api/groups.html#share-groups-with-groups

### CODE REVIEW

**Review by GrahamCampbell — CHANGES_REQUESTED** [review]
Thanks for taking the time to prepare this, and sorry for my delayed review. Are you able to add a couple of tests please?

**Comment by GrahamCampbell** [comment]
Friendly ping @peterjaap.

**Comment by peterjaap** [comment]
@GrahamCampbell sorry I don't have the time / headspace to write tests atm.

**Comment by GrahamCampbell** [comment]
No problem, if you wanna come back to this later in the year, or not at all, both are fine. :)

**Pull request closed without merging**
