### PR TITLE
Pagination of Project Members

### PR DESCRIPTION
**Pull request by tobiasetter**
GitLab API per default defines 20 items per_page for the returned result. Now if a project has more than 20 members we have an issue with increasing the number of items to max i.e. 100.

Therefore I complemented your code.

Many thanks!

### CODE REVIEW

**Comment by fbourigault** [comment]
Thank you for your contribution. Could you use the `OptionsResolver` like in https://github.com/m4tthumphrey/php-gitlab-api/blob/master/lib/Gitlab/Api/Projects.php#L35?

However, you have to do a little more work to not break BC. You will have to accept `$username_query` to be a string or an array and if it's a string, use it like the current code + trigger a deprecation notice. If it's an array or a null value, treat it as the argument you have to pass to `OptionsResolver::resolve`.

**Comment by tobiasetter** [comment]
I had to remove deprecated notice, because it was catched by build ci.

Maybe you know another way to implement this deprecation notice. Thanks

**Comment by fbourigault** [comment]
You have to write `@trigger_error(..`.

**Comment by tobiasetter** [comment]
@fbourigault thanks for your help. what do you think about a merge?

**Comment by m1guelpf** [comment]
@fbourigault This is a breaking change. Maybe find a way to make it backwards-compatible?

**Comment by tobiasetter** [comment]
@fbourigault What are the next steps? Do you want to merge or do we have to find a way to make it backwards-compatible as @m1guelpf suggested?

**Comment by tobiasetter** [comment]
@m1guelpf In order to make it backwards compatible would you remove the error throwing?

**Comment by tobiasetter** [comment]
now it would also close issue #259 

pull requests #310 and #286 both are resolved by this pull request

**Comment by m1guelpf** [comment]
@tobiasetter Can you fix the tests?

**Comment by tobiasetter** [comment]
@m1guelpf what do you mean? all tests were successful

**Comment by m1guelpf** [comment]
@tobiasetter Sorry, I meant merge conflicts

**Comment by tobiasetter** [comment]
@m1guelpf Sure, no problem =)

**Comment by m1guelpf** [comment]
@tobiasetter Thank you for your contribution!

**Comment by tobiasetter** [comment]
@m1guelpf how about creating a new release?

**Pull request merged**
