### PR TITLE
[11.10] Add ProjectBoard and ProjectBoardList API

### PR DESCRIPTION
**Pull request by pkolmann**
Added missing API calls regarding project boards:

* addBoard: https://docs.gitlab.com/ee/api/boards.html#create-an-issue-board
* updateBoard: https://docs.gitlab.com/ee/api/boards.html#update-an-issue-board
* removeBoard: https://docs.gitlab.com/ee/api/boards.html#delete-an-issue-board

Also add API calls for board lists:

* boardLists: https://docs.gitlab.com/ee/api/boards.html#list-board-lists-in-a-project-issue-board
* addBoardList: https://docs.gitlab.com/ee/api/boards.html#create-a-board-list
* reorderBoardList: https://docs.gitlab.com/ee/api/boards.html#reorder-a-list-in-a-board
* removeBoardList: https://docs.gitlab.com/ee/api/boards.html#delete-a-board-list-from-a-board

### CODE REVIEW

**Comment by pkolmann** [comment]
@GrahamCampbell please consider this pull request and advise what to improve to be able to merge.
Thanks

**Review by GrahamCampbell — CHANGES_REQUESTED** [review]
Thanks for the PR. Please add parameter validation, phpdoc and tests, then I will consider this for merge. 🎉

**Review by GrahamCampbell — CHANGES_REQUESTED** [review]
Please add parameter validation, phpdoc and tests, then I will consider this for merge.

**Comment by pkolmann** [comment]
I have just found that the necessary functionality has already been implemented in https://github.com/GitLabPHP/Client/blob/11.10/src/Api/IssueBoards.php#L51

Therefore this PR is obsolete and I'll close it.

Sorry for the hassle.

**Pull request closed without merging**
