### PR TITLE
[11.9] Add support for `Projects::pipelineTestReport` & `Projects::pipelineTestReportSummary`

### PR DESCRIPTION
**Pull request by jdecool**
Add support for:
* https://docs.gitlab.com/ee/api/pipelines.html#get-a-pipelines-test-report
* https://docs.gitlab.com/ee/api/pipelines.html#get-a-pipelines-test-report-summary

### CODE REVIEW

**Comment by jdecool** [comment]
🖖🏼  Hey @GrahamCampbell , don't want to put pressure, just want to know if you plan to merge this PR ?

**Comment by jdecool** [comment]
Hi @GrahamCampbell, do you think this is mergeable ?

**Comment by GrahamCampbell** [comment]
Thanks for working on this. 🎉

**Comment by GrahamCampbell** [comment]
v11.9.0 has now been released, with this change, and many others, including PHP 8.2 support. 🚢

**Pull request merged**
