### PR TITLE
fix members request with empty query.

### PR DESCRIPTION
**Pull request by Artistan**
members request does not require query and is actually broken right now if you provide an empty query
https://gitlab.com/gitlab-com/support-forum/issues/2878

### CODE REVIEW

**Comment by m1guelpf** [comment]
@fbourigault Wouldn't this be fixed using `OptionsResolver`?

**Comment by Artistan** [comment]
@m1guelpf - how is this?  I think you still need to check if null?

**Comment by fbourigault** [comment]
Could you add a test to ensure we are not sending a `null` query?

**Comment by tobiasetter** [comment]
@fbourigault @m1guelpf @Artistan This pull request would also be resolved by my pull request: #281

**Pull request merged**
