### PR TITLE
Added compare method

### PR DESCRIPTION
**Pull request by CSchulz**
see https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/repositories.md#compare-branches-tags-or-commits

### CODE REVIEW

**Comment by zanematthew** [comment]
Maybe I'm over looking something here, but for me compare always returns a 404.

Given I have the following tags for a project: `$client->api('repositories')->tags(17);`

The output looks like the following:

```
 [0] => Array
        (
            [name] => v1.2.1
            [commit] => Array
                (
                    [id] => e11b95246e8bd1bb7261d4c675bf222e12134dc6
                    [parents] => Array
                        (
                            [0] => Array
                                (
                                    [id] => bb367a1724c8548f2c861568db6caea86a3e3f66
                                )
                        )
                    [tree] => 746ee8443063ba5f368db93e9ce85f7e8a0f2360
                    [message] => Updating version number
                    [authored_date] => 2015-01-13T16:57:23+00:00
                    [committed_date] => 2015-01-13T16:57:23+00:00
                )
        )

    [1] => Array
        (
            [name] => v1.2.0
            [commit] => Array
                (
                    [id] => 39ce51975551d516b4fa7b058ea48503bb713b14
                    [parents] => Array
                        (
                            [0] => Array
                                (
                                    [id] => 3005207e12a9627a00ba480fe5986d3a96db322a
                                )
                        )
                    [tree] => 7c66e611a24d4ca85dbf1382c2a3f84948a4a6e2
                    [message] => Updating latest...                  
                )
            [protected] => 
        )
```

Then I should be able to compare two tags, and view all commits from v1.1.2 to v1.2.1 using; `$client->api('repositories')->compare( 17, '1aba5eb73', 'e11b95246' );`, but this actually returns a 404.

**Comment by m4tthumphrey** [comment]
Hey @zanematthew, I've just checked this on my Gitlab install and it's working as expected. Are you sure you have the project ID correct? Also you need to make sure the two refs are in the correct order, so `from` needs to be before `to` in chronological order.

**Comment by zanematthew** [comment]
Thanks for checking!

I'm going over things seeing if I missed anything, as other parts of the API are working great. Honestly maybe I'm thinking compare does something different, and/or my hashes are wrong.

Currently in a git you can do `$ git log [sha/tag/branch]..[sha/tag/branch]` to view all commits between those two. I've elaborated on it to build out my changelogs, via this one liner; 

```git log --pretty=format:" * %s, %ad" --date=short v1.2.0..v1.2.1 | grep "@changelog" | sed 's/, @changelog//g' > changelog.md```

What I'm looking to do is automate this via the webhook using compare; pull in the commits, parse, and write to disk.

This should be possible with compare right? Granted I can't pass in a tag.

As of know I've double checked the following:

* Project ID – For this I've pulled in a list of projects via http://doc.gitlab.com/ce/api/projects.html, and assumed that first `id` shown is in fact the project ID, I've also tried using the project name with namespace in single quotes.
* User/owner – I've double checked that my GitLabs user has owner/rights to the repository.
* From/to – Double checked the order, and I've tried using the full hash 39ce51975551d516b4fa7b058ea48503bb713b14, and the 7 char length one

Are there any other places I'm overlooking?

**Comment by m4tthumphrey** [comment]
Hmm very strange. You are right in the expected behaviour, the `compare()` method returns the following response:

```
{
    "commit": {
        "id": "ed86a689af39ed2b6414dd0f6afdda4812cee0e2",
        "short_id": "ed86a689",
        "title": "Added is() and deleteFeature() methods",
        "author_name": "Matt Humphrey",
        "author_email": "matth@windsor-telecom.co.uk",
        "created_at": "2015-02-17T15:47:06.000+00:00",
        "message": "Added is() and deleteFeature() methods\n"
    },
    "commits": [
        {
            "id": "e990c8cdafa1c5df82b505c928d6cb72770eb9d7",
            "short_id": "e990c8cd",
            "title": "Ability to detect withheld numbers in VIP / call barring features",
            "author_name": "Matt Humphrey",
            "author_email": "matth@windsor-telecom.co.uk",
            "created_at": "2015-01-14T11:28:11.000+00:00",
            "message": "Ability to detect withheld numbers in VIP / call barring features\n"
        }
        // ...
    ],
    "diffs": [
        {
            "old_path": "src/Windsor/Document/AbstractValidator.php",
            "new_path": "src/Windsor/Document/AbstractValidator.php",
            "a_mode": "100644",
            "b_mode": "100644",
            "diff": "..... text based diff ....",
            "new_file": false,
            "renamed_file": false,
            "deleted_file": false
        }
        // ...
    ],
    "compare_timeout": false,
    "compare_same_ref": false
}
```

The next obvious question to me is what version of Gitlab are you running? The comparing of refs via the API was only introduced in [Gitlab 7.0](https://github.com/gitlabhq/gitlabhq/commit/f441436e53377f207657ac0e0e518e5ee2b33a6c#diff-5767a622392d17258b90dada42e974ac).

**Comment by zanematthew** [comment]
Genius! I had a feeling I had overlooked something.

>The next obvious question to me is what version of Gitlab are you running? The comparing of refs via the API was only introduced in Gitlab 7.0.

I'm on GitLab 6.7.3-1.

Thanks for the tip, on being able to compare tags.

**Comment by m4tthumphrey** [comment]
No worries man. I'd definitely try and keep up with keeping Gitlab up to date - the development cycle is very fast but the new features are worth it!

**Comment by zanematthew** [comment]
Just wanted to let you know it worked, after I updated to the latest GitLabs. Actually did a fresh install on a new EC2 and ported everything over. I was using a Bitnami stack prior :| and switched to the Omnibus, have to say install was a breeze.

**Comment by m4tthumphrey** [comment]
:+1:

**Pull request merged**
