### PR TITLE
[11.9] Feature/groups issues

### PR DESCRIPTION
**Pull request by macbookandrew**
Also includes #707

### CODE REVIEW

**Comment by hbjydev** [comment]
@macbookandrew Any ETA on getting this merged?

**Comment by macbookandrew** [comment]
@hbjydev I haven’t heard anything. @GrahamCampbell is the maintainer, so it’s up to him

**Review by 20uf — APPROVED** [review]

**Comment by macbookandrew** [comment]
@GrahamCampbell could you review this when you get a chance?

**Comment by GrahamCampbell** [comment]
Awesome. Thanks for your contribution. 🎉 🚀

**Comment by GrahamCampbell** [comment]
v11.9.0 has now been released, with this change, and many others, including PHP 8.2 support. 🚢

**Pull request merged**
