### PR TITLE
Allow use of search parameter for merge requests

### PR DESCRIPTION
**Pull request by velichkin**
It's possible to use search parameter for merge-requests. The only change is to add to $resolver.

### CODE REVIEW

**Comment by velichkin** [comment]
ping @m4tthumphrey

**Comment by fbourigault** [comment]
`search` seems to be undocumented for merge requests. I don't like so much adding undocumented Gitlab API stuff as it may be considered as internal.

Do you have some references about the existence of this `search` parameter?

**Comment by velichkin** [comment]
I've checked it and it works. But, unfortunately, I haven't found it in official API.

**Comment by fbourigault** [comment]
@m4tthumphrey @m1guelpf what is your point of view about undocumented Gitlab API features support in this library?

**Comment by velichkin** [comment]
Here is the discussion about this parameter - https://gitlab.com/gitlab-org/gitlab-ce/issues/38318

**Comment by velichkin** [comment]
https://gitlab.com/gitlab-org/gitlab-ce/issues/38318

**Comment by fbourigault** [comment]
Thank you!

**Pull request merged**
