### PR TITLE
[11.1] Add order_by and sort params support to Deployments::all()

### PR DESCRIPTION
**Pull request by b1rdex**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks for this. Could you:

- [x] Rebase against 11.1
- [x] Add a couple of tests
- [x] Add an entry to the change log (which is what requires you to rebase)

**Comment by b1rdex** [comment]
What kind of tests am I supposed to write? Would be nice to see an example.

**Comment by GrahamCampbell** [comment]
Please look at the existing tests. :)

**Comment by GrahamCampbell** [comment]
https://github.com/GitLabPHP/Client/pull/615/files would be a helpful example of doing exactly this.

**Comment by b1rdex** [comment]
@GrahamCampbell done

**Comment by GrahamCampbell** [comment]
Excellent, thanks.

**Pull request merged**
